# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 	pod 'LFLiveKit', :git => 'http://192.168.8.20/vender-ios/LFLiveKit.git', :branch => 'master'

end
